version: "3.8"
services:
  api-server:
    build: .
    env_file:
      - ./.env
    image: quiz-api
    networks:
      - quiz
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src

  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mariadb:10.6
    networks:
      - quiz
    restart: always
    volumes:
      - api-data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    image: phpmyadmin:5
    networks:
      - quiz
    ports:
      - 8080:80
    restart: always

networks:
  quiz:
    driver: bridge
volumes:
  api-data:
    driver: local
